
package algoritmogenetico;


import java.awt.Dimension;
import java.awt.Graphics;



import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class PanelADN extends javax.swing.JPanel {

    public void paintComponent(Graphics g) {
        Dimension tamanio = getSize();
        ImageIcon imagenFondo = new ImageIcon(getClass().
                getResource("/Imagenes/ARN.jpg"));
        g.drawImage(imagenFondo.getImage(), 0, 0,
                tamanio.width, tamanio.height, null);
        setOpaque(false);

        super.paintComponent(g);

    }

    /** Creates new form PanelADN */
    public PanelADN() {
          
        M = new String[1000][1000];
        initComponents();
        this.setSize(800, 1000);




    }

    public void imprimirreinas(Vector v) {
        String texto = "";
        String matrizA = "\n";
        for (int i = 0; i < v.size(); i++) {
            for (int j = 0; j < v.size(); j++) {
                if (v.elementAt(j).equals(i)) {
                    M[i][j] = "╬";
                    matrizA += "   " + M[i][j];

                } else {
                    if ((i + j) % 2 == 0) {
                        M[i][j] = "█";
                    } else {
                        M[i][j] = "░";
                    }

                    matrizA += "   " + M[i][j];
                }

            }
            matrizA += "\n";
        }

        texto = "[Matriz de cromosomas]" + matrizA + " " + texto + "\n";
        JTPoblacionInicial.append(texto);
        JTPoblacionInicial.append("       " + "\n");

//        System.out.println(texto);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        jtxtTasadeCruzamiento = new javax.swing.JTextField();
        jtxtTasadeMutacion = new javax.swing.JTextField();
        jtFPoblacion = new javax.swing.JTextField();
        jtFCanReinas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlbl = new javax.swing.JLabel();
        jtxtIteraciones = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTPoblacionInicial = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtGeneracion = new javax.swing.JTextArea();
        jtxtMejorResultado = new javax.swing.JTextField();
        jtxtMejorUtilidad = new javax.swing.JTextField();
        jtxtGeneraciones = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10.png"))); // NOI18N
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jtxtTasadeCruzamiento.setText("1");

        jtxtTasadeMutacion.setText("0.1");

        jtFPoblacion.setText("5");

        jtFCanReinas.setText("4");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8.png"))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reinas.png"))); // NOI18N

        jlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/21.png"))); // NOI18N

        jtxtIteraciones.setText("20");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/22.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/23.png"))); // NOI18N

        JTPoblacionInicial.setColumns(20);
        JTPoblacionInicial.setRows(5);
        JTPoblacionInicial.setToolTipText("Con 4 reinas se puede ver\n las amenazas en el tablero\n o utilidad");
        jScrollPane1.setViewportView(JTPoblacionInicial);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        jtGeneracion.setColumns(20);
        jtGeneracion.setRows(5);
        jScrollPane2.setViewportView(jtGeneracion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciar, 0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtMejorUtilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jtxtMejorResultado)
                                    .addComponent(jtxtGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxtIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jtxtTasadeCruzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jtFPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(46, 46, 46)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(65, 65, 65)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jtFCanReinas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTasadeMutacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtFCanReinas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtFPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTasadeCruzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTasadeMutacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtxtMejorResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtMejorUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
    
        JTPoblacionInicial.setText("");
        jtGeneracion.setText("");
        Double tasadecruce;
        tasadecruce = Double.parseDouble(jtxtTasadeCruzamiento.getText());
        Double tasademutacion;
        tasademutacion = Double.parseDouble(jtxtTasadeMutacion.getText());

        int nropobla = Integer.parseInt(jtFPoblacion.getText());
        int reinas = Integer.parseInt(jtFCanReinas.getText());
        Vector v = new Vector();
        List<CromosomaNreinas> poblacion;
        poblacion = new ArrayList<CromosomaNreinas>();
        AlgoritmogeneticoNreinas ab = new AlgoritmogeneticoNreinas();
        for (int i = 0; i < nropobla; i++) {
            poblacion.add(i, ab.generarpoblacioninicial(reinas, v));
        }
        System.out.println("Poblacion INICIAL");
        for (CromosomaNreinas cro : poblacion) {

            System.out.println(cro.getUtilidad());
            JTPoblacionInicial.append("Utilidad :" + String.valueOf(cro.getUtilidad()) + "\n");
            System.out.println(cro.getV());
            JTPoblacionInicial.append("Vector Cromosoma :" + cro.getV().toString() + "\n");
            jtGeneracion.append("Vector Cromosoma :" + cro.getV().toString() + " Utilidad :" + String.valueOf(cro.getUtilidad()) + "\n");
            imprimirreinas(cro.getV());
        }

        /////////////////////////////////////////////////////////////////////////////
        int iteraciones = 0;
        int Padres = nropobla - 1;
        while (iteraciones < Integer.parseInt(jtxtIteraciones.getText())) {
            AlgoritmogeneticoNreinas a = new AlgoritmogeneticoNreinas();
            a.setPadres(Padres);
            //a.seleccionruleta( poblacion);
            a.setHijos(new ArrayList<CromosomaNreinas>());
            a.GenerarDescendencia(tasadecruce, tasademutacion, poblacion, a.getPadres());//Se ingresa tasa de cruzamiento
            jtGeneracion.append("\n" + "Poblacion Ordenada" + "\n");

            for (CromosomaNreinas cromo : a.getPoblacionordenada()) {

                jtGeneracion.append("Vector Cromosoma :" + cromo.getV().toString() + " Utilidad: " + cromo.getUtilidad() + "\n");

            }
            jtGeneracion.append("\n" + "El mejor: " + a.getMejorfitness().getV());
            jtGeneracion.append("\n" + "Cantidad de Padres Seleccionados: " + a.getPadres());
            jtGeneracion.append("\n" + "Combinatoria total de Hijos: " + a.getCombinatoriadehijos());
            jtGeneracion.append("\n" + "Tasa de cruzamiento: " + jtxtTasadeCruzamiento.getText());
            jtGeneracion.append("\n" + "Cantidad de Hijos cruzados: (" + jtxtTasadeCruzamiento.getText() + "*" + a.getPadres() + ")≈ "
                    + a.getCantidadhijoscruzados());
            jtGeneracion.append("\n" + "Copias de Padres(menor igual a): " + a.getPadres());
            jtGeneracion.append("\n" + "Tasa de Mutacion: " + jtxtTasadeMutacion.getText());
            jtGeneracion.append("\n" + "Cantidad de Hijos Mutados:(" + jtxtTasadeMutacion.getText() + "*" + a.getCantidadhijoscruzados() + ")≈ "
                    + a.getCantidadhijosmutados());
            jtGeneracion.append("\n" + "Hijos" + "\n");
            jtGeneracion.append("Linea de Cruce : " + String.valueOf(a.getLineadecruce()) + "\n");
            for (CromosomaNreinas cro : a.getHijos()) {
                jtGeneracion.append(cro.getV() + "Utilidad :" + cro.getUtilidad() + " (" + cro.getEstado() + ")" + "\n");
            }

            poblacion = a.getHijos();
            iteraciones++;
            System.out.println(iteraciones);
            jtxtMejorResultado.setText(a.getMejorfitness().getV().toString());
            jtxtMejorUtilidad.setText(String.valueOf(a.getMejorfitness().getUtilidad()));
         
        }


        ///////////////////////////////////////////////////////////////

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTPoblacionInicial;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbl;
    private javax.swing.JTextField jtFCanReinas;
    private javax.swing.JTextField jtFPoblacion;
    private javax.swing.JTextArea jtGeneracion;
    private javax.swing.JTextField jtxtGeneraciones;
    private javax.swing.JTextField jtxtIteraciones;
    private javax.swing.JTextField jtxtMejorResultado;
    private javax.swing.JTextField jtxtMejorUtilidad;
    private javax.swing.JTextField jtxtTasadeCruzamiento;
    private javax.swing.JTextField jtxtTasadeMutacion;
    // End of variables declaration//GEN-END:variables
    public String[][] M;
  
}
